echo "==> Building Trigger > Pentest > Services menu..."

oniomarchy_menu_jsonc="$HOME/.config/omarchy/extensions/omarchy-menu.jsonc"
oniomarchy_services_generated="$HOME/.local/state/oniomarchy/services-menu-entries.tsv"

if [[ ! -f $oniomarchy_services_generated ]]; then
  echo "==> [services/menu] $oniomarchy_services_generated missing — run verify-units.sh first" >&2
  exit 1
fi

mkdir -p "$(dirname "$oniomarchy_menu_jsonc")"
[[ -f $oniomarchy_menu_jsonc ]] || echo -e "{\n}" > "$oniomarchy_menu_jsonc"

# JSON-string-escape a value (backslash and double-quote only).
oniomarchy_svc_jesc() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '%s' "$s"
}

# Nested under the already-built trigger.pentest submenu (own BEGIN/END
# marker block, independent of install/trigger/menu.sh's own block — both
# coexist in the same jsonc file, same pattern as security/menu.sh +
# trigger/menu.sh already do). Briefly relocated to security.services.*
# the same session, then reverted back here per user request after
# comparing both live — trigger.pentest.services.* is the one that
# stuck. Icon codepoints stored as hex, not hand-typed glyphs (see
# feedback_pua_glyph_transcription memory) — confirmed present in the
# installed JetBrainsMono Nerd Font's cmap before use: fa-server
# (0xF233), fa-play (0xF04B), fa-stop (0xF04D), fa-refresh (0xF021).
oniomarchy_services_icon=$(printf '%b' '\UF233')
oniomarchy_start_icon=$(printf '%b' '\UF04B')
oniomarchy_stop_icon=$(printf '%b' '\UF04D')
oniomarchy_restart_icon=$(printf '%b' '\UF021')

oniomarchy_block_file=$(mktemp)
trap 'rm -f "$oniomarchy_block_file"' RETURN

{
  echo "  // BEGIN oniomarchy services menu (generated by install/services/menu.sh)"
  printf '  "trigger.pentest.services": {"icon":"%s","label":"Services"},\n' \
    "$(oniomarchy_svc_jesc "$oniomarchy_services_icon")"

  while IFS=$'\t' read -r id label confirm unit1 unit2; do
    [[ -z $id ]] && continue

    oniomarchy_checked="systemctl is-active --quiet $unit1"
    [[ -n $unit2 ]] && oniomarchy_checked+=" && systemctl is-active --quiet $unit2"

    printf '  "trigger.pentest.services.%s": {"icon":"%s","label":"%s","checked":"%s"},\n' \
      "$(oniomarchy_svc_jesc "$id")" \
      "$(oniomarchy_svc_jesc "$oniomarchy_services_icon")" \
      "$(oniomarchy_svc_jesc "$label")" \
      "$(oniomarchy_svc_jesc "$oniomarchy_checked")"

    for entry in "start:Start:$oniomarchy_start_icon" "stop:Stop:$oniomarchy_stop_icon" "restart:Restart:$oniomarchy_restart_icon"; do
      oniomarchy_action_name="${entry%%:*}"
      oniomarchy_rest="${entry#*:}"
      oniomarchy_action_label="${oniomarchy_rest%%:*}"
      oniomarchy_action_icon="${oniomarchy_rest#*:}"

      oniomarchy_units="$unit1"
      [[ -n $unit2 ]] && oniomarchy_units+=" $unit2"

      # Stop never confirms even for sshd/xrdp (only start/restart can newly
      # expose the service) — service-confirm-action.sh itself also enforces
      # this, this is just which target script/UI path gets used.
      if [[ $confirm == yes ]]; then
        oniomarchy_action="omarchy-launch-tui bash -c 'sudo service-confirm-action \"$label\" $oniomarchy_action_name $oniomarchy_units; exec bash'"
      else
        oniomarchy_action="pkexec service-action $oniomarchy_action_name $oniomarchy_units"
      fi

      printf '  "trigger.pentest.services.%s.%s": {"icon":"%s","label":"%s","action":"%s"},\n' \
        "$(oniomarchy_svc_jesc "$id")" \
        "$oniomarchy_action_name" \
        "$(oniomarchy_svc_jesc "$oniomarchy_action_icon")" \
        "$(oniomarchy_svc_jesc "$oniomarchy_action_label")" \
        "$(oniomarchy_svc_jesc "$oniomarchy_action")"
    done
  done < "$oniomarchy_services_generated"

  echo "  // END oniomarchy services menu"
} > "$oniomarchy_block_file"

oniomarchy_merged=$(mktemp)
awk -v blockfile="$oniomarchy_block_file" '
  BEGIN {
    in_block = 0
    while ((getline line < blockfile) > 0) block = block line "\n"
  }
  /\/\/ BEGIN oniomarchy services menu/ { in_block = 1; next }
  /\/\/ END oniomarchy services menu/ { in_block = 0; next }
  in_block { next }
  /^}[[:space:]]*$/ && !inserted {
    printf "%s", block
    inserted = 1
  }
  { print }
' "$oniomarchy_menu_jsonc" > "$oniomarchy_merged"

mv "$oniomarchy_merged" "$oniomarchy_menu_jsonc"

echo "==> Services menu written to $oniomarchy_menu_jsonc"
