echo "==> Building Security Tools menu..."

oniomarchy_security_generated="$HOME/.local/state/oniomarchy/security-menu-entries.tsv"
oniomarchy_menu_jsonc="$HOME/.config/omarchy/extensions/omarchy-menu.jsonc"

if [[ ! -f $oniomarchy_security_generated ]]; then
  echo "==> [security/menu] $oniomarchy_security_generated not found — run verify-binaries.sh first" >&2
  return 1 2>/dev/null || exit 1
fi

mkdir -p "$(dirname "$oniomarchy_menu_jsonc")"
[[ -f $oniomarchy_menu_jsonc ]] || echo -e "{\n}" > "$oniomarchy_menu_jsonc"

# JSON-string-escape a value (backslash and double-quote only — none of our
# labels/actions currently contain control characters).
oniomarchy_jesc() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '%s' "$s"
}

# Static submenu tree: id, icon codepoint (hex — as literal glyphs these are
# Nerd Font Private Use Area characters, too easy to mistranscribe by hand,
# so they're stored as hex and converted with printf below), label. Every
# codepoint here was copied from a real entry in
# /usr/share/omarchy/default/omarchy/omarchy-menu.jsonc (see
# notes/install-layout.md) — reused, not invented. Root "security" first,
# then one row per category in notes/pentest-tools.md's Menu Tree.
# Software Defined Radio reuses Wireless Attacks' F16BE (Wi-Fi) glyph —
# that source file has no dedicated radio/antenna icon, and reusing an
# already-confirmed codepoint is the established pattern here (EB11 and
# F06F3 are each already reused across two categories above). AI Tools
# reuses the stock menu's own "install.ai" entry's F16A4 glyph — added
# 2026-08-28 once hexstrike-ai got a real install script (see
# install/apps/ai-tools/hexstrike-ai.sh); previously omitted here since no
# omarchy-pkg-installable tool existed in that category yet.
oniomarchy_security_submenus=(
  "security|EB11|Security"
  "security.infogather|F06F3|Info Gathering"
  "security.vuln|F0237|Vuln Analysis"
  "security.web|F268|Web App Analysis"
  "security.password|EB11|Password Attacks"
  "security.wireless|F16BE|Wireless Attacks"
  "security.sdr|F16BE|SDR"
  "security.re|EBA2|Reverse Eng"
  "security.exploit|F16A1|Exploitation Tools"
  "security.sniff|F06F3|Sniff & Spoof"
  "security.postex|F489|Post Exploitation"
  "security.forensics|F02CA|Digital Forensics"
  "security.reporting|F044|Reporting Tools"
  "security.social|F066F|Social Engineering"
  "security.automotive|EF70|Automotive"
  "security.ai|F16A4|AI Tools"
  "security.webapps|F268|Webapps"
)

declare -A oniomarchy_category_icon

oniomarchy_block_file=$(mktemp)
trap 'rm -f "$oniomarchy_block_file"' RETURN

{
  echo "  // BEGIN oniomarchy security menu (generated by install/security/menu.sh — edit install/security/categories.tsv instead of this block)"

  for row in "${oniomarchy_security_submenus[@]}"; do
    IFS='|' read -r id icon_hex label <<< "$row"
    icon=$(printf '%b' "\\U${icon_hex}")
    short_id="${id#security.}"
    [[ $short_id == "$id" ]] && short_id="root"
    oniomarchy_category_icon["$short_id"]="$icon"
    printf '  "%s": {"icon":"%s","label":"%s"},\n' \
      "$id" "$(oniomarchy_jesc "$icon")" "$(oniomarchy_jesc "$label")"
  done

  # Subcategories (multi-binary packages) declared by verify-binaries.sh.
  # 4 fields: SUBCAT, category, subcat_id, label.
  while IFS=$'\t' read -r kind category subcat_id label; do
    [[ $kind == SUBCAT ]] || continue
    icon="${oniomarchy_category_icon[$category]:-}"
    printf '  "security.%s.%s": {"icon":"%s","label":"%s"},\n' \
      "$category" "$subcat_id" "$(oniomarchy_jesc "$icon")" "$(oniomarchy_jesc "$label")"
  done < "$oniomarchy_security_generated"

  # Leaf entries. 7 fields: ENTRY, category, subcat, id_slug, label, action, alias.
  while IFS=$'\t' read -r kind category subcat id_slug label action alias; do
    [[ $kind == ENTRY ]] || continue
    icon="${oniomarchy_category_icon[$category]:-}"
    if [[ $subcat == "-" ]]; then
      full_id="security.${category}.${id_slug}"
    else
      full_id="security.${category}.${subcat}.${id_slug}"
    fi
    if [[ $alias != "-" && $alias != "$label" ]]; then
      printf '  "%s": {"icon":"%s","label":"%s","aliases":["%s"],"action":"%s"},\n' \
        "$full_id" "$(oniomarchy_jesc "$icon")" "$(oniomarchy_jesc "$label")" "$(oniomarchy_jesc "$alias")" "$(oniomarchy_jesc "$action")"
    else
      printf '  "%s": {"icon":"%s","label":"%s","action":"%s"},\n' \
        "$full_id" "$(oniomarchy_jesc "$icon")" "$(oniomarchy_jesc "$label")" "$(oniomarchy_jesc "$action")"
    fi
  done < "$oniomarchy_security_generated"

  # Webapps — a separate pipeline from the categories.tsv/verify-binaries.sh
  # rows above (these aren't pacman packages, installed instead by
  # install/security/install-webapps.sh via `omarchy webapp install`), but
  # get their own submenu here per "Decision: Webapps get their own menu"
  # in notes/pentest-tools.md. Only emits an entry for a webapp whose
  # .desktop file actually exists — same "no guessing/no entry for
  # something not actually installed" rule verify-binaries.sh applies to
  # pacman packages above.
  oniomarchy_webapps_tsv="$ONIOMARCHY_INSTALL/security/webapps.tsv"
  if [[ -f $oniomarchy_webapps_tsv ]]; then
    webapps_icon="${oniomarchy_category_icon[webapps]:-}"
    while IFS=$'\t' read -r id_slug label url tactic icon; do
      [[ -z $id_slug || $id_slug == \#* ]] && continue
      if [[ ! -f "$HOME/.local/share/applications/$label.desktop" ]]; then
        echo "==> [security/menu] webapp '$label' not installed yet — skipping" >&2
        continue
      fi
      printf '  "security.webapps.%s": {"icon":"%s","label":"%s","action":"%s"},\n' \
        "$id_slug" "$(oniomarchy_jesc "$webapps_icon")" "$(oniomarchy_jesc "$label")" \
        "$(oniomarchy_jesc "uwsm-app -- omarchy-launch-webapp '$url'")"
    done < "$oniomarchy_webapps_tsv"
  fi

  echo "  // END oniomarchy security menu"
} > "$oniomarchy_block_file"

oniomarchy_merged=$(mktemp)
awk -v blockfile="$oniomarchy_block_file" '
  BEGIN {
    in_block = 0
    while ((getline line < blockfile) > 0) block = block line "\n"
  }
  /\/\/ BEGIN oniomarchy security menu/ { in_block = 1; next }
  /\/\/ END oniomarchy security menu/ { in_block = 0; next }
  in_block { next }
  /^}[[:space:]]*$/ && !inserted {
    printf "%s", block
    inserted = 1
  }
  { print }
' "$oniomarchy_menu_jsonc" > "$oniomarchy_merged"

mv "$oniomarchy_merged" "$oniomarchy_menu_jsonc"

echo "==> Security Tools menu written to $oniomarchy_menu_jsonc"
