echo "==> Building Trigger > Pentest menu..."

oniomarchy_menu_jsonc="$HOME/.config/omarchy/extensions/omarchy-menu.jsonc"

mkdir -p "$(dirname "$oniomarchy_menu_jsonc")"
[[ -f $oniomarchy_menu_jsonc ]] || echo -e "{\n}" > "$oniomarchy_menu_jsonc"

# JSON-string-escape a value (backslash and double-quote only).
oniomarchy_jesc() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '%s' "$s"
}

# Nested under the existing `trigger` root (not a new top-level category —
# see notes/trigger-menu.md for why: default root items always sort before
# extension-file items, so a new root id could never move earlier anyway;
# nesting under `trigger` sidesteps that entirely, same trick as this repo's
# `apps.antigravity` entry). Icon codepoints stored as hex, not hand-typed
# glyphs (see feedback_pua_glyph_transcription memory) — fa-crosshairs
# (0xF05B), confirmed present in the installed JetBrainsMono Nerd Font's
# cmap before use.
oniomarchy_pentest_icon=$(printf '%b' '\UF05B')

oniomarchy_block_file=$(mktemp)
trap 'rm -f "$oniomarchy_block_file"' RETURN

{
  echo "  // BEGIN oniomarchy trigger menu (generated by install/trigger/menu.sh)"
  printf '  "trigger.pentest": {"icon":"%s","label":"Pentest"},\n' "$(oniomarchy_jesc "$oniomarchy_pentest_icon")"

  # Tor: no trigger.pentest entry here anymore — replaced 2026-08-27 by the
  # third-party `tormarchy` Omarchy plugin (see notes/pentest-tools.md's
  # Anonymity section), which ships its own bar panel with a right-click
  # toggle. That's the equivalent this repo would otherwise be building
  # here, so a duplicate menu action isn't worth carrying.

  # MAC randomization: no trigger.pentest entry here anymore — replaced
  # 2026-08-27 by the third-party `macarchy` Omarchy plugin (see
  # notes/pentest-tools.md's Anonymity section), which ships its own bar
  # panel with per-interface Randomize/Restore/Set and a Restore All
  # escape hatch. Same reasoning as dropping the archtorify menu entry
  # above: a duplicate menu action isn't worth carrying.

  # Reverse-shell listener: single entry, interactive port prompt (per
  # user decision — see notes/trigger-menu.md), rather than a few preset
  # ports. Uses ncat (from nmap, already installed) rather than the
  # classic nc binary (from openbsd-netcat, also installed per user
  # request but not used here) — user's own call, ncat has the better
  # feature set (SSL, proxying) and its -lvnp flags behave the same for
  # this use. No separate installed script/leaf needed: no root required
  # to listen on a normal (>1024) port, so the whole thing is inline in
  # the action string. Port entry uses `omarchy-menu-input` (a real
  # installed Omarchy helper — /usr/share/omarchy/bin/omarchy-menu-input —
  # that summons the same themed omarchy.menu widget as other Omarchy
  # prompts) instead of a plain terminal `read`, per user request; only
  # once a port is actually entered does it open a terminal
  # (`omarchy-launch-tui`) to run the listener itself, since ncat needs to
  # stay open/interactive there.
  if command -v ncat >/dev/null 2>&1; then
    oniomarchy_revshell_icon=$(printf '%b' '\UF120')
    oniomarchy_revshell_action='port=$(omarchy-menu-input "Port") && [ -n "$port" ] && exec omarchy-launch-tui bash -c "ncat -lvnp $port; exec bash"'
    printf '  "trigger.pentest.revshell": {"icon":"%s","label":"Reverse Shell Listener","action":"%s"},\n' \
      "$(oniomarchy_jesc "$oniomarchy_revshell_icon")" \
      "$(oniomarchy_jesc "$oniomarchy_revshell_action")"
  else
    echo "==> [trigger/menu] ncat not available — skipping trigger.pentest.revshell entry" >&2
  fi

  echo "  // END oniomarchy trigger menu"
} > "$oniomarchy_block_file"

oniomarchy_merged=$(mktemp)
awk -v blockfile="$oniomarchy_block_file" '
  BEGIN {
    in_block = 0
    while ((getline line < blockfile) > 0) block = block line "\n"
  }
  /\/\/ BEGIN oniomarchy trigger menu/ { in_block = 1; next }
  /\/\/ END oniomarchy trigger menu/ { in_block = 0; next }
  in_block { next }
  /^}[[:space:]]*$/ && !inserted {
    printf "%s", block
    inserted = 1
  }
  { print }
' "$oniomarchy_menu_jsonc" > "$oniomarchy_merged"

mv "$oniomarchy_merged" "$oniomarchy_menu_jsonc"

echo "==> Trigger > Pentest menu written to $oniomarchy_menu_jsonc"
