echo "==> Building Trigger > Pentest menu..."

oniomarchy_menu_jsonc="$HOME/.config/omarchy/extensions/omarchy-menu.jsonc"

mkdir -p "$(dirname "$oniomarchy_menu_jsonc")"
[[ -f $oniomarchy_menu_jsonc ]] || echo -e "{\n}" > "$oniomarchy_menu_jsonc"

# JSON-string-escape a value (backslash and double-quote only).
oniomarchy_jesc() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '%s' "$s"
}

# Nested under the existing `trigger` root (not a new top-level category —
# see notes/trigger-menu.md for why: default root items always sort before
# extension-file items, so a new root id could never move earlier anyway;
# nesting under `trigger` sidesteps that entirely, same trick as this repo's
# `apps.antigravity` entry). Icon codepoints stored as hex, not hand-typed
# glyphs (see feedback_pua_glyph_transcription memory) — fa-crosshairs
# (0xF05B), confirmed present in the installed JetBrainsMono Nerd Font's
# cmap before use.
oniomarchy_pentest_icon=$(printf '%b' '\UF05B')

oniomarchy_block_file=$(mktemp)
trap 'rm -f "$oniomarchy_block_file"' RETURN

{
  echo "  // BEGIN oniomarchy trigger menu (generated by install/trigger/menu.sh)"
  printf '  "trigger.pentest": {"icon":"%s","label":"Pentest"},\n' "$(oniomarchy_jesc "$oniomarchy_pentest_icon")"

  # Tor: no trigger.pentest entry here anymore — replaced 2026-08-27 by the
  # third-party `tormarchy` Omarchy plugin (see notes/pentest-tools.md's
  # Anonymity section), which ships its own bar panel with a right-click
  # toggle. That's the equivalent this repo would otherwise be building
  # here, so a duplicate menu action isn't worth carrying.

  # MAC randomization: no trigger.pentest entry here anymore — replaced
  # 2026-08-27 by the third-party `macarchy` Omarchy plugin (see
  # notes/pentest-tools.md's Anonymity section), which ships its own bar
  # panel with per-interface Randomize/Restore/Set and a Restore All
  # escape hatch. Same reasoning as dropping the archtorify menu entry
  # above: a duplicate menu action isn't worth carrying.

  # Reverse-shell listener: single entry, interactive port prompt (per
  # user decision — see notes/trigger-menu.md), rather than a few preset
  # ports. Uses ncat (from nmap, already installed) rather than the
  # classic nc binary (from openbsd-netcat, also installed per user
  # request but not used here) — user's own call, ncat has the better
  # feature set (SSL, proxying) and its -lvnp flags behave the same for
  # this use. No separate installed script/leaf needed: no root required
  # to listen on a normal (>1024) port, so the whole thing is inline in
  # the action string. Port entry uses `omarchy-menu-input` (a real
  # installed Omarchy helper — /usr/share/omarchy/bin/omarchy-menu-input —
  # that summons the same themed omarchy.menu widget as other Omarchy
  # prompts) instead of a plain terminal `read`, per user request; only
  # once a port is actually entered does it open a terminal
  # (`omarchy-launch-tui`) to run the listener itself, since ncat needs to
  # stay open/interactive there.
  if command -v ncat >/dev/null 2>&1; then
    oniomarchy_revshell_icon=$(printf '%b' '\UF120')
    oniomarchy_revshell_action='port=$(omarchy-menu-input "Port") && [ -n "$port" ] && exec omarchy-launch-tui bash -c "ncat -lvnp $port; exec bash"'
    printf '  "trigger.pentest.revshell": {"icon":"%s","label":"Reverse Shell Listener","action":"%s"},\n' \
      "$(oniomarchy_jesc "$oniomarchy_revshell_icon")" \
      "$(oniomarchy_jesc "$oniomarchy_revshell_action")"
  else
    echo "==> [trigger/menu] ncat not available — skipping trigger.pentest.revshell entry" >&2
  fi

  # Quick HTTP file server: prompts for a directory (blank = $HOME) and a
  # port (blank = 8000, python's own default), then opens a terminal running
  # python3 -m http.server from that directory. Uses python3 explicitly
  # (not python) since this machine's mise shim sits ahead of system python
  # on PATH — see CLAUDE.md's mise note — and python3 is unaffected.
  # Foreground in the terminal like revshell: closing the window kills the
  # server, nothing lingers as a background daemon.
  if command -v python3 >/dev/null 2>&1; then
    oniomarchy_httpserver_icon=$(printf '%b' '\UF019')
    oniomarchy_httpserver_action='dir=$(omarchy-menu-input "Directory (blank = home)") && dir="${dir:-$HOME}" && port=$(omarchy-menu-input "Port (blank = 8000)") && port="${port:-8000}" && exec omarchy-launch-tui bash -c "cd \"$dir\" && python3 -m http.server $port; exec bash"'
    printf '  "trigger.pentest.http-server": {"icon":"%s","label":"HTTP File Server","action":"%s"},\n' \
      "$(oniomarchy_jesc "$oniomarchy_httpserver_icon")" \
      "$(oniomarchy_jesc "$oniomarchy_httpserver_action")"
  else
    echo "==> [trigger/menu] python3 not available — skipping trigger.pentest.http-server entry" >&2
  fi

  # Trust proxy CA: fetch an intercepting proxy's CA certificate and add it
  # to the system trust store, so Firefox/Chromium/curl stop throwing
  # certificate errors on every HTTPS page routed through Burp or Caido.
  #
  # Deliberately a menu action rather than an install.sh step: Burp serves
  # its CA at http://127.0.0.1:8080/cert only while Burp is actually
  # running, so there is nothing to fetch at install time. See
  # install/trigger/proxy-trust.sh.
  #
  # sudo (not pkexec) because omarchy-launch-tui gives it a real terminal
  # and the operator should see exactly which certificate got trusted —
  # this writes to the system trust store. Matches the privilege rule in
  # CLAUDE.md: sudo for terminal-visible actions, pkexec only for
  # background GUI actions with nowhere to prompt.
  #
  # Icon: md-certificate (0xF0811), confirmed present in the installed
  # JetBrainsMono Nerd Font's cmap before use, stored as hex rather than a
  # hand-typed glyph (see feedback_pua_glyph_transcription memory).
  if command -v oniomarchy-proxy-trust >/dev/null 2>&1; then
    oniomarchy_proxytrust_icon=$(printf '%b' '\UF0811')
    oniomarchy_proxytrust_action='port=$(omarchy-menu-input "Proxy port (blank = 8080, Burp)") && port="${port:-8080}" && exec omarchy-launch-tui bash -c "sudo oniomarchy-proxy-trust $port; exec bash"'
    printf '  "trigger.pentest.proxy-trust": {"icon":"%s","label":"Trust Proxy CA","action":"%s"},\n' \
      "$(oniomarchy_jesc "$oniomarchy_proxytrust_icon")" \
      "$(oniomarchy_jesc "$oniomarchy_proxytrust_action")"
  else
    echo "==> [trigger/menu] oniomarchy-proxy-trust not installed — skipping trigger.pentest.proxy-trust entry" >&2
  fi

  echo "  // END oniomarchy trigger menu"
} > "$oniomarchy_block_file"

oniomarchy_merged=$(mktemp)
awk -v blockfile="$oniomarchy_block_file" '
  BEGIN {
    in_block = 0
    while ((getline line < blockfile) > 0) block = block line "\n"
  }
  /\/\/ BEGIN oniomarchy trigger menu/ { in_block = 1; next }
  /\/\/ END oniomarchy trigger menu/ { in_block = 0; next }
  in_block { next }
  /^}[[:space:]]*$/ && !inserted {
    printf "%s", block
    inserted = 1
  }
  { print }
' "$oniomarchy_menu_jsonc" > "$oniomarchy_merged"

mv "$oniomarchy_merged" "$oniomarchy_menu_jsonc"

echo "==> Trigger > Pentest menu written to $oniomarchy_menu_jsonc"
